#端口
server:
  port: 8055

#应用信息
spring:
  application:
    name: mhq0123-officialwebsite-edgeservice

  #默认开发
  profiles:
    active: dev

#注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8077/eureka/

#设置断路器的超时（默认1s）
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeout-InMilliseconds: 5000

#日志
logging:
  config: classpath:logback-spring.xml
  path: /root/mhq0123-officialwebsite/logs/${spring.application.name}
  file: ${spring.application.name}

#开发
---
spring:
  profiles: dev

---
#生产
spring:
  profiles: prod