#端口
server:
  port: 80

#应用信息
spring:
  application:
    name: mhq0123-officialwebsite-gateway

#注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8777/eureka/

#日志
logging:
  config: classpath:logback.xml

#路由信息,多个节点时自动集成ribbon负载均衡
zuul:
  routes:
    mhq0123-officialwebsite-blog-web:
      path: /blog/**
      service-id: mhq0123-officialwebsite-blog-web
    mhq0123-officialwebsite-scheduler-web:
      path: /scheduler/**
      service-id: mhq0123-officialwebsite-scheduler-web