#端口
server:
  port: 80

#应用信息
spring:
  application:
    name: mhq0123-officialwebsite-web-client

  #默认开发
  profiles:
    active: dev

#开发
---
spring:
  profiles: dev

#日志
logging:
  config: classpath:logback-dev.xml

---
#生产
spring:
  profiles: prod

logging:
  config: classpath:logback-prod.xml