#端口
server:
  port: 80

#应用信息
spring:
  application:
    name: mhq0123-officialwebsite-web-client

  #默认开发
  profiles:
    active: dev

#日志
logging:
  config: classpath:logback-spring.xml
  path: /root/mhq0123-officialwebsite/logs/${spring.application.name}
  file: ${spring.application.name}

#开发
---
spring:
  profiles: dev

---
#生产
spring:
  profiles: prod
