#服务端口
server:
  port: 8888

spring:
  #名称
  application:
    name: mhq0123-officialwebsite-config

  #从src/main/resource下检索配置
  profiles:
    active: native

  #健康检查
  cloud:
    config:
      server:
        health:
          enabled: true

#rabbitmq
  rabbitmq:
    host: localhost
    port: 5672
    username: mhq0123-officialwebsite
    password: 123456

##开启用户名密码验证
#security:
#  user:
#    role: whole
#    name: user
#    password: 123456

#注册服务
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8777/eureka/

#日志
logging:
  config: classpath:logback.xml

