#端口
server:
  port: 8000

#应用信息
spring:
  application:
    name: mhq0123-officialwebsite-microservice-customer

  #默认开发
  profiles:
    active: dev

#注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8077/eureka/

#开发
---
spring:
  profiles: dev

#日志
logging:
  config: classpath:logback-dev.xml

---
#生产
spring:
  profiles: prod

logging:
  config: classpath:logback-prod.xml