#端口
server:
  port: 8000

#应用信息
spring:
  application:
    name: mhq0123-officialwebsite-assistant-web

  #默认开发
  profiles:
    active: dev

#注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8777/eureka/

#设置断路器的超时（默认1s）
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeout-InMilliseconds: 5000

#开发
---
spring:
  profiles: dev

  #开发关闭缓存
  thymeleaf:
    cache: false

server:
  tomcat:
    access_log_enabled: true
    basedir: target/tomcat

#日志
logging:
  config: classpath:logback-dev.xml



---
#生产
spring:
  profiles: prod

  #生产打开缓存
  thymeleaf:
    cache: true

logging:
  config: classpath:logback-prod.xml